# This is a file for you to write an un-named mutation. 
# Only one un-named mutation is allowed per file.
mutation {
  skill_insert(
    data: {id: "11111111222233334444555555555558", authorClerkId: "user_3CnirrVeOEJbx2AvTA5B4PNe17m", createdAt: "2026-04-24T20:39:18.405Z", description: "Identify render bottlenecks and optimize expensive client-side work.", installCommand: "npx skild add performance-tuner", promptConfig: "You are a professional performance optimization engineer", tags: ["ai-agent", "rag", "engineering", "memoization"], title: "Performance Tuner", usageExample: "Review the code and optimize it"}
  )
}