# 1. User Table
type User @table(key: "clerkId") {
    clerkId: String! @unique
    email: String!
    username: String
    imageUrl: String
}

# 2. Skill Table
type Skill @table(key: "id") {
  id: UUID! @default(expr: "uuidV4()")
  
  # Relationship
  author: User!

  # Skill Content
  title: String!
  description: String!
  tags: [String!]!

  # Technical
  installCommand: String!
  promptConfig: String!
  usageExample: String!
  
  # Meta Data
  createdAt: Timestamp! @default(expr: "request.time")
}
